name: Run Tests
on:
  push:
    branches:
      - master
  workflow_call: # Make this workflow callable from other workflows

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare App
        uses: ./.github/workflows/prepare-app

      - name: Prepare Test Environment
        run: |
          sudo apt-get install sshpass
          sudo mkdir ~/.ssh
          sudo touch ~/.ssh/known_hosts

      # TODO Use --coverage ? (only available directly at the pest command)
      #      Maybe see here: https://medium.com/@vlreshet/how-to-setup-phpunit-coverage-report-and-phpstan-report-using-github-actions-and-github-wiki-pages-86effdfd8c53
      - name: Run Tests
        run: php artisan test --exclude-group=long-running,wip -v
